version: "3.8"

services:
  ngn:
    env_file: 
      - .env
    image: nginx:1.0
    container_name: nginx
    depends_on:
      - wdp
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - lol
    volumes:
      - wdata:/var/www/html
    restart: always

  mdb:
    env_file: 
      - .env
    image: mariadb:1.0
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mdata:/var/lib/mysql
    networks:
      - lol
    restart: always
  
  wdp:
    env_file: .env
    image: wordpress:1.0
    container_name: wordpress
    depends_on:
      - mdb
    build: ./requirements/wordpress
    volumes:
      - wdata:/var/www/html
    networks:
      - lol
    restart: always

  rds:
    image: redis:1.0
    container_name: redis
    build: ./requirements/bonus/redis
    networks:
      - lol
    restart: always
  
  admnr:
    env_file:
      - .env
    image: adminer:1.0
    container_name: adminer
    build: ./requirements/bonus/adminer
    depends_on:
      - mdb
    networks:
      - lol

  ftp:
    env_file:
      - .env
    image: ftp:1.0
    container_name: ftp
    build: ./requirements/bonus/ftp
    ports:
      - 21:21
      - "21100-21110:21100-21110"
    networks:
      - lol
    restart: always


volumes:
  wdata:
    name: wdata
    driver_opts:
      device: /home/faksouss/data/wdata
      o: bind
      type: none
  mdata:
    name: mdata
    driver_opts:
      device: /home/faksouss/data/mdata
      o: bind
      type: none

networks:
  lol:
    driver: bridge