# Use the official Debian Buster as a base image
FROM debian:buster

# Install NGINX and OpenSSL
RUN apt-get update && \
    apt-get install -y nginx openssl && \
    rm -rf /var/lib/apt/lists/*

# Generate SSL certificate and key
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=MA/ST=BENIMALAL-KHNEFRA/L=KHOURIBGA/O=Example/CN=example.com"

# Remove the default NGINX configuration
RUN rm /etc/nginx/nginx.conf

# Copy your custom NGINX configuration file
COPY tools/nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 443

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
