# Use the official Debian Buster as a base image
FROM debian:buster

# Install NGINX and OpenSSL
RUN apt-get update && \
    apt-get install -y nginx openssl

RUN rm /etc/nginx/nginx.conf

RUN mkdir -p /etc/nginx/sites-enabled

COPY tools/nginx.conf /etc/nginx/sites-enabled/

# Changing the working directory
WORKDIR /etc/nginx

# Get the shell script to set the ssl certification and key
COPY tools/setssl.sh setssl.sh

# Generate SSL certificate and key and remove the default config file
RUN chmod 777 setssl.sh && ./setssl.sh && \
    rm setssl.sh

# Copy your custom NGINX configuration file
COPY tools/nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 443

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
