FROM debian:buster

RUN apt-get update -y && apt-get install -y nginx openssl

EXPOSE 443

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt -subj "/C=MA/ST=Bnimalal-Khonifra/L=Khouribga/O=LEET/CN=faksouss.42.fr"

COPY conf/default.conf /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]
